company_name = "Tops Technologies pvt Ltd"
# ans=company_name.lower()
# print(ans)
# ans=company_name.upper()
# print(ans)
# ans=company_name.title()
# print(ans)
# ans=company_name.capitalize()
# print(ans)
# ans=len(company_name)
# print(ans)
# ans=company_name.count("o")
# print(ans)
# ans=company_name.count("o",4,7)
# print(ans)
ans=company_name.split(".")
print(ans)
ans=company_name.startswith("Tops")
print(ans)
ans=company_name.endswith("ltd")
print(ans)
ans=company_name.find("T",3)
print(ans)
ans=company_name.replace("Tech","AI")
print(ans)
ans=company_name.strip()
print(ans)
ans=" ".join("tech")
print(ans)
ans="testtech".isalpha()
print(ans)
ans="1232323 4".isdigit()
print(ans)
ans="12#$we3rt12".isalnum()
print(ans)
print(len(company_name))
ans=company_name.zfill(50)
print(ans)
ans=company_name[0:5:2]
print(ans)