lst_numbers=[1,22,44,55,67,22,22,22]
lst_numbers.insert(0,45)
print(lst_numbers)
#lst_numbers.clear()
#print(lst_numbers)
lst_new=lst_numbers.copy()
print("New list ",lst_new)
lst_numbers.insert(3,22890)
print(lst_numbers)
print("New list ",lst_new)
print(lst_numbers.count(55))
lst_odd=[89,75,55,45]
lst_numbers.extend(lst_odd)
print(lst_numbers)
ind=lst_numbers.index(22)
print(ind)
lst_numbers.pop()
print(lst_numbers)
lst_numbers.remove(22)
print(lst_numbers)

lst_numbers.reverse()
print(lst_numbers)
lst_numbers.sort()
print(lst_numbers)
lst_numbers.sort(reverse=True)
print(lst_numbers)